version: '3'
services:
  server:
    container_name: server
    build: .
    ports:
      - 8080:80
    volumes:
      - ./html:/var/www/html
  database:
    container_name: database
    image: mariadb:11.1
    ports:
      - 3306:3306
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 1234
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.2
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_ARBITRARY: 1