version: '3'
services:
  server:
    container_name: server
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./html:/var/www/html
  database:
    container_name: database
    image: mariadb:11.1
    ports:
      - 3306:3306
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: biblioteca
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.2
    restart: always
    ports:
      - 8001:80
    environment:
      PMA_ARBITRARY: 1
  # nginx:
  #   image: nginx:1.17-alpine
  #   container_name: nginx
  #   restart: unless-stopped
  #   ports:
  #     - 9000:80
  #   volumes:
  #     - ./html:/var/www
  #     - ./nginx:/etc/nginx/conf.d